import { requireSupabase } from '../supabase.js';
import { $ } from './shared.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function deviceInfo(){const ua=navigator.userAgent;let device='Máy tính';if(/Android/i.test(ua))device='Android';else if(/iPhone|iPad/i.test(ua))device='iPhone/iPad';return `${device} · ${navigator.platform||''} · ${navigator.language||''}`}
async function daySnapshot(date){if(!date)return[];const r=await requireSupabase().from('shifts').select('id,sales_date,shift,employee_id,note,employees(name),shift_toppings(topping_type_id,quantity)').eq('sales_date',date).order('shift');return r.error?[]:r.data||[]}
function compact(rows){return rows.map(r=>({id:r.id,shift:r.shift,employee:r.employees?.name||'',employee_id:r.employee_id,note:r.note||'',toppings:(r.shift_toppings||[]).map(x=>({id:x.topping_type_id,quantity:Number(x.quantity)||0}))}))}
async function logLoginOnce(){const key=`topping:login:${new Date().toISOString().slice(0,13)}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');try{const c=requireSupabase(),s=await c.auth.getSession(),u=s.data?.session?.user;if(!u)return;await c.from('login_logs').insert({user_id:u.id,email:u.email||'',device_info:deviceInfo(),user_agent:navigator.userAgent})}catch(e){console.warn('Không ghi được login log',e)}}
async function loadLogs(){const out=$('#featureLoginLogs');if(!out)return;out.innerHTML='<p class="muted">Đang tải...</p>';const c=requireSupabase();const [lr,ar]=await Promise.all([c.from('login_logs').select('email,device_info,created_at').order('created_at',{ascending:false}).limit(30),c.from('audit_logs').select('action,entity,entity_id,sales_date,details,created_at').order('created_at',{ascending:false}).limit(50)]);let html='<h4>Lịch sử đăng nhập</h4>';html+=lr.error?`<p class="feature-warning">${esc(lr.error.message)}</p>`:(lr.data||[]).map(x=>`<div style="padding:8px 0;border-bottom:1px solid #eee"><strong>${esc(x.email||'')}</strong><br><small>${new Date(x.created_at).toLocaleString('vi-VN')} · ${esc(x.device_info||'')}</small></div>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>';html+='<h4 style="margin-top:18px">Nhật ký chỉnh sửa</h4>';html+=ar.error?`<p class="feature-warning">${esc(ar.error.message)}</p>`:(ar.data||[]).map(x=>`<details style="padding:8px 0;border-bottom:1px solid #eee"><summary><strong>${esc(x.action||'')}</strong> · ${esc(x.entity||'')} · ${new Date(x.created_at).toLocaleString('vi-VN')}</summary><small>${x.sales_date?'Ngày '+esc(x.sales_date):''}</small><pre style="white-space:pre-wrap;max-height:260px;overflow:auto">${esc(JSON.stringify(x.details||{},null,2))}</pre></details>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>';out.innerHTML=html}
function captureSaveAudit(){const form=$('#shiftForm');if(!form||form.dataset.auditCapture==='1')return;form.dataset.auditCapture='1';form.addEventListener('submit',async()=>{const date=$('#shiftDate')?.value||'',before=compact(await daySnapshot(date));setTimeout(async()=>{try{const c=requireSupabase(),s=await c.auth.getSession(),u=s.data?.session?.user,after=compact(await daySnapshot(date));await c.from('audit_logs').insert({user_id:u?.id||null,user_email:u?.email||'',action:'save',entity:'shift_day',sales_date:date,details:{message:`Lưu dữ liệu ngày ${date}`,before,after}})}catch(e){console.warn('Không ghi được audit',e)}},1200)},true)}
function boot(){const host=$('#feature-tools-host');if(!host||host.dataset.auditReady==='1')return;host.dataset.auditReady='1';const s=document.createElement('section');s.className='feature-panel';s.innerHTML=`<div class="feature-toolbar" style="justify-content:space-between"><div><h3>Đăng nhập & nhật ký thay đổi</h3><p class="muted">Ghi thiết bị và snapshot trước/sau khi lưu.</p></div><button class="feature-btn" id="featureRefreshAudit">Làm mới</button></div><div id="featureLoginLogs"></div>`;host.appendChild(s);$('#featureRefreshAudit').onclick=loadLogs;captureSaveAudit();logLoginOnce();loadLogs()}
boot();
