import { requireSupabase } from '../supabase.js';
import { $, notify } from './shared.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function deviceInfo(){const ua=navigator.userAgent;let device='Máy tính';if(/Android/i.test(ua))device='Android';else if(/iPhone|iPad/i.test(ua))device='iPhone/iPad';return `${device} · ${navigator.platform||''} · ${navigator.language||''}`}
async function logLoginOnce(){const key=`topping:login:${new Date().toISOString().slice(0,13)}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');try{const c=requireSupabase(),s=await c.auth.getSession(),u=s.data?.session?.user;if(!u)return;await c.from('login_logs').insert({user_id:u.id,email:u.email||'',device_info:deviceInfo(),user_agent:navigator.userAgent})}catch(e){console.warn('Không ghi được login log',e)}}
async function loadLogs(){const out=$('#featureLoginLogs');if(!out)return;out.innerHTML='<p class="muted">Đang tải...</p>';const c=requireSupabase();const [lr,ar]=await Promise.all([c.from('login_logs').select('email,device_info,created_at').order('created_at',{ascending:false}).limit(30),c.from('audit_logs').select('action,entity,entity_id,sales_date,details,created_at').order('created_at',{ascending:false}).limit(50)]);let html='<h4>Lịch sử đăng nhập</h4>';html+=lr.error?`<p class="feature-warning">${esc(lr.error.message)}</p>`:(lr.data||[]).map(x=>`<div style="padding:8px 0;border-bottom:1px solid #eee"><strong>${esc(x.email||'')}</strong><br><small>${new Date(x.created_at).toLocaleString('vi-VN')} · ${esc(x.device_info||'')}</small></div>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>';html+='<h4 style="margin-top:18px">Nhật ký chỉnh sửa</h4>';html+=ar.error?`<p class="feature-warning">${esc(ar.error.message)}</p>`:(ar.data||[]).map(x=>`<div style="padding:8px 0;border-bottom:1px solid #eee"><strong>${esc(x.action||'')}</strong> · ${esc(x.entity||'')}<br><small>${new Date(x.created_at).toLocaleString('vi-VN')} ${x.sales_date?'· '+esc(x.sales_date):''}</small><div>${esc(x.details?.message||JSON.stringify(x.details||{}))}</div></div>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>';out.innerHTML=html}
async function captureSaveAudit(){const form=$('#shiftForm');if(!form||form.dataset.auditCapture==='1')return;form.dataset.auditCapture='1';form.addEventListener('submit',async()=>{const date=$('#shiftDate')?.value||'';setTimeout(async()=>{try{const c=requireSupabase(),s=await c.auth.getSession(),u=s.data?.session?.user;await c.from('audit_logs').insert({user_id:u?.id||null,user_email:u?.email||'',action:'save',entity:'shift_day',sales_date:date,details:{message:`Lưu dữ liệu ngày ${date}`}})}catch{}},800)},true)}
function boot(){const host=$('#feature-tools-host');if(!host||host.dataset.auditReady==='1')return;host.dataset.auditReady='1';const s=document.createElement('section');s.className='feature-panel';s.innerHTML=`<div class="feature-toolbar" style="justify-content:space-between"><div><h3>Đăng nhập & nhật ký thay đổi</h3><p class="muted">Theo dõi tài khoản, thiết bị và các lần lưu dữ liệu.</p></div><button class="feature-btn" id="featureRefreshAudit">Làm mới</button></div><div id="featureLoginLogs"></div>`;host.appendChild(s);$('#featureRefreshAudit').onclick=loadLogs;captureSaveAudit();logLoginOnce();loadLogs()}
boot();
