import { requireSupabase } from '../supabase.js';
import { $, notify, fetchMonthRows, rowQuantity } from './shared.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
async function exportExcel(){const month=$('#recordsMonth')?.value||new Date().toISOString().slice(0,7),rows=await fetchMonthRows(month);const body=rows.map(r=>`<tr><td>${r.sales_date}</td><td>${r.shift}</td><td>${esc(r.employees?.name||'')}</td><td>${rowQuantity(r)}</td><td>${rowQuantity(r)*1000}</td><td>${esc(r.note||'')}</td></tr>`).join('');const html=`<html><head><meta charset="utf-8"></head><body><table border="1"><tr><th>Ngày</th><th>Ca</th><th>Nhân viên</th><th>Topping</th><th>Tiền</th><th>Ghi chú</th></tr>${body}</table></body></html>`;download(`topping-${month}.xls`,new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}));notify('Đã xuất file Excel.')}
async function exportPdf(){const month=$('#recordsMonth')?.value||new Date().toISOString().slice(0,7),rows=await fetchMonthRows(month),w=window.open('','_blank','width=950,height=720');if(!w)return alert('Trình duyệt đang chặn cửa sổ in.');w.document.write(`<html><head><meta charset="utf-8"><title>Báo cáo ${month}</title><style>body{font-family:Arial;padding:24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:7px}</style></head><body><h1>Báo cáo topping ${month}</h1><table><tr><th>Ngày</th><th>Ca</th><th>Nhân viên</th><th>Topping</th><th>Tiền</th></tr>${rows.map(r=>`<tr><td>${r.sales_date}</td><td>${r.shift}</td><td>${esc(r.employees?.name||'')}</td><td>${rowQuantity(r)}</td><td>${rowQuantity(r)*1000}</td></tr>`).join('')}</table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function backupJson(){const month=$('#recordsMonth')?.value||new Date().toISOString().slice(0,7),rows=await fetchMonthRows(month);download(`backup-topping-${month}.json`,new Blob([JSON.stringify({version:1,month,created_at:new Date().toISOString(),rows},null,2)],{type:'application/json'}));notify('Đã backup JSON.')}
async function restoreJson(file){if(!file)return;let data;try{data=JSON.parse(await file.text())}catch{return alert('File JSON không hợp lệ.')}if(!Array.isArray(data.rows))return alert('Backup không có dữ liệu rows.');if(!confirm(`Khôi phục ${data.rows.length} dòng? Dữ liệu trùng có thể bị Supabase từ chối.`))return;const c=requireSupabase();for(const row of data.rows){const x=await c.rpc('save_shift',{p_shift_id:null,p_sales_date:row.sales_date,p_shift:row.shift,p_employee_id:row.employee_id,p_note:row.note||'',p_toppings:(row.shift_toppings||[]).map(t=>({topping_type_id:t.topping_type_id,quantity:t.quantity}))});if(x.error&&!/duplicate|unique/i.test(x.error.message||'')){console.error(x.error)}}notify('Đã chạy khôi phục backup.');setTimeout(()=>location.reload(),600)}
function boot(){const host=$('#feature-tools-host');if(!host||host.dataset.exportReady==='1')return;host.dataset.exportReady='1';const s=document.createElement('section');s.className='feature-panel';s.innerHTML=`<h3>Xuất & Backup</h3><div class="feature-toolbar"><button class="feature-btn" id="featureExcel">Xuất Excel</button><button class="feature-btn" id="featurePdf">In / PDF</button><button class="feature-btn" id="featureBackupJson">Backup JSON</button><label>Restore JSON<input id="featureRestoreJson" type="file" accept="application/json,.json"></label></div>`;host.appendChild(s);$('#featureExcel').onclick=exportExcel;$('#featurePdf').onclick=exportPdf;$('#featureBackupJson').onclick=backupJson;$('#featureRestoreJson').onchange=e=>restoreJson(e.target.files?.[0])}
boot();
