import { requireSupabase } from '../supabase.js';
import { $, notify } from './shared.js';

const state={lastError:null};
window.addEventListener('error',e=>{state.lastError=e.message||'Lỗi JavaScript'});
window.addEventListener('unhandledrejection',e=>{state.lastError=e.reason?.message||String(e.reason||'Promise bị lỗi')});
async function check(){const host=$('#feature-system-health');if(!host)return;host.innerHTML='<p class="muted">Đang kiểm tra...</p>';let supabase='OK',version='dev',latency='-';const start=performance.now();try{const r=await requireSupabase().from('employees').select('id',{head:true,count:'exact'}).limit(1);if(r.error)throw r.error;latency=`${Math.round(performance.now()-start)} ms`}catch(e){supabase=`Lỗi: ${e.message}`;state.lastError=e.message}try{const r=await fetch('./version.json',{cache:'no-store'}),j=await r.json();version=j.version||j.commit||version}catch{}host.innerHTML=`<div class="feature-grid"><div class="feature-card"><small>Supabase</small><strong>${supabase==='OK'?'Online':'Có lỗi'}</strong><span>${supabase}</span></div><div class="feature-card"><small>Độ trễ</small><strong>${latency}</strong></div><div class="feature-card"><small>Phiên bản</small><strong>${version}</strong></div><div class="feature-card"><small>Lỗi gần nhất</small><strong style="font-size:14px">${state.lastError||'Không có'}</strong></div></div>`}
async function checkUpdate(){try{const r=await fetch('./version.json',{cache:'no-store'}),j=await r.json(),current=localStorage.getItem('topping:last-version');if(current&&j.version&&current!==j.version)notify(`Có bản cập nhật mới: ${j.version}`);if(j.version)localStorage.setItem('topping:last-version',j.version)}catch{}}
function boot(){const host=$('#feature-settings-host');if(!host||host.dataset.healthReady==='1')return;host.dataset.healthReady='1';const s=document.createElement('section');s.className='feature-panel';s.innerHTML=`<div class="feature-toolbar" style="justify-content:space-between"><div><h3>Hoạt động hệ thống</h3><p class="muted">Kiểm tra kết nối, phiên bản và lỗi gần nhất.</p></div><button class="feature-btn" id="featureHealthRefresh">Kiểm tra lại</button></div><div id="feature-system-health"></div>`;host.appendChild(s);$('#featureHealthRefresh').onclick=check;check();checkUpdate()}
boot();
