drop table if exists public.audit_logs cascade;

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  record_id text,
  changed_by uuid default auth.uid(),
  old_data jsonb,
  new_data jsonb,
  changed_at timestamptz not null default now()
);

create index audit_logs_changed_at_idx on public.audit_logs (changed_at desc);
create index audit_logs_table_record_idx on public.audit_logs (table_name, record_id);

alter table public.audit_logs enable row level security;

create policy "managers read audit logs" on public.audit_logs
for select to authenticated
using (public.current_app_role() = 'manager');

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  rid text;
begin
  if tg_op = 'DELETE' then
    rid := coalesce(to_jsonb(old)->>'id', to_jsonb(old)->>'shift_id', '');
    insert into public.audit_logs(table_name, action, record_id, changed_by, old_data, new_data)
    values (tg_table_name, tg_op, rid, (select auth.uid()), to_jsonb(old), null);
    return old;
  elsif tg_op = 'UPDATE' then
    rid := coalesce(to_jsonb(new)->>'id', to_jsonb(new)->>'shift_id', '');
    insert into public.audit_logs(table_name, action, record_id, changed_by, old_data, new_data)
    values (tg_table_name, tg_op, rid, (select auth.uid()), to_jsonb(old), to_jsonb(new));
    return new;
  else
    rid := coalesce(to_jsonb(new)->>'id', to_jsonb(new)->>'shift_id', '');
    insert into public.audit_logs(table_name, action, record_id, changed_by, old_data, new_data)
    values (tg_table_name, tg_op, rid, (select auth.uid()), null, to_jsonb(new));
    return new;
  end if;
end;
$$;

create trigger audit_shifts_changes after insert or update or delete on public.shifts
for each row execute function public.write_audit_log();

create trigger audit_shift_toppings_changes after insert or update or delete on public.shift_toppings
for each row execute function public.write_audit_log();

create trigger audit_employees_changes after insert or update or delete on public.employees
for each row execute function public.write_audit_log();
